spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stablepay
    username: stablepay
    password: stablepay
  jpa:
    show-sql: true

logging:
  level:
    com.stablepay: DEBUG
    org.hibernate.SQL: DEBUG
